Detect compressed files which contain tar files to prevent writing archives to disks

diff --git a/sdrestore b/sdrestore
--- a/sdrestore
+++ b/sdrestore
@@ -167,6 +167,12 @@ else
   RESTOREFILE="$FILE"
 fi
 
+# Check its not still compressed
+if [[ "`file \"$RESTOREFILE\" | grep 'compressed\|archive'`" ]]; then
+  echo "Error: Cannot decompress $FILE" 1>&2;
+  exit 1;
+fi
+
 # Restore the file
 echo "Restoring "`ls -lah "$RESTOREFILE" | awk -F " " {'print $5'}`" to $DEV..."
 echo
